package com.example.hospital.admin;
import com.example.hospital.auth.*;
import com.example.hospital.common.*;
import java.time.*;
import java.math.BigDecimal;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AdminService {
    private final AdminMapper db;private final UserMapper users;private final PasswordEncoder encoder;private final Clock clock;
    public AdminService(AdminMapper db,UserMapper users,PasswordEncoder encoder,Clock clock){this.db=db;this.users=users;this.encoder=encoder;this.clock=clock;}
    public Map<String,Object> query(Map<String,String> input,boolean publicOnly){Map<String,Object> p=new HashMap<>(input);int page=Math.max(1,Integer.parseInt(input.getOrDefault("page","1"))),size=Math.max(1,Math.min(100,Integer.parseInt(input.getOrDefault("size","20"))));p.put("size",size);p.put("offset",Math.multiplyExact(page-1,size));p.put("publicOnly",publicOnly);p.put("now",LocalDateTime.now(clock));p.put("today",LocalDate.now(clock));p.put("lastDay",LocalDate.now(clock).plusDays(6));return p;}
    @Audit("账户创建") @Transactional public Object createUser(Map<String,Object> in){Actor.current().require("ADMIN");var p=new HashMap<>(in);String name=Rows.required(p,"username",64);if(!name.matches("[A-Za-z0-9_]{4,64}"))throw new BizException("用户名应为4～64位字母、数字或下划线");p.put("username",name);p.put("display_name",Rows.required(p,"display_name",80));String role=Rows.str(p,"role");if(!List.of("PATIENT","DOCTOR","CASHIER","PHARMACIST","ADMIN").contains(role))throw new BizException("角色无效");String password=Rows.required(p,"password",72);if(password.length()<8)throw new BizException("密码至少8位");p.put("password_hash",encoder.encode(password));users.insert(p);if(role.equals("PATIENT")){p.put("phone",Rows.str(p,"phone"));users.patient(p);}return users.byId(Rows.longVal(p,"id"));}
    @Audit("账户状态修改") @Transactional public Object updateUser(long id,Map<String,Object> in){Actor a=Actor.current();a.require("ADMIN");if(id==a.id())throw new BizException("不能通过管理接口修改当前登录账户");var old=users.byId(id);if(old==null)throw new BizException("账户不存在");var p=new HashMap<String,Object>();p.put("id",id);p.put("enabled",in.getOrDefault("enabled",old.get("enabled")));String pw=Rows.str(in,"password");if(!pw.isBlank()){if(pw.length()<8||pw.length()>72)throw new BizException("密码长度需为8～72位");p.put("password_hash",encoder.encode(pw));}db.updateUser(p);return users.byId(id);}
    @Audit("科室维护") @Transactional public Object department(Long id,Map<String,Object> in){Actor.current().require("ADMIN");var p=new HashMap<>(in);p.put("name",Rows.required(p,"name",100));p.putIfAbsent("location","");p.putIfAbsent("description","");p.putIfAbsent("enabled",true);if(id==null)db.addDepartment(p);else{p.put("id",id);if(db.updateDepartment(p)==0)throw new BizException("科室不存在");}return Map.of("id",p.get("id"));}
    @Audit("医生维护") @Transactional public Object doctor(Long id,Map<String,Object> in){Actor.current().require("ADMIN");var p=new HashMap<>(in);p.put("department_id",Rows.longVal(p,"department_id"));p.putIfAbsent("title","");p.putIfAbsent("specialty","");p.putIfAbsent("enabled",true);if(id==null){var user=users.byId(Rows.longVal(p,"user_id"));if(user==null||!"DOCTOR".equals(user.get("role")))throw new BizException("请选择医生角色账户");db.addDoctor(p);}else{if(db.lockDoctor(id)==null)throw new BizException("医生不存在");p.put("id",id);db.updateDoctor(p);}return Map.of("id",p.get("id"));}
    @Audit("排班维护") @Transactional public Object schedule(Long id,Map<String,Object> in){Actor.current().require("ADMIN");var p=new HashMap<>(in);long doctor=Rows.longVal(p,"doctor_id");var d=db.lockDoctor(doctor);if(d==null||!Rows.bool(d,"enabled"))throw new BizException("医生不存在或已停用");var start=Rows.dateTime(p,"start_time");var end=Rows.dateTime(p,"end_time");LocalDate day=LocalDate.parse(Rows.str(p,"work_date"));if(!start.toLocalDate().equals(day)||!end.toLocalDate().equals(day)||!end.isAfter(start))throw new BizException("时段必须在同一天且结束晚于开始");int total=Rows.intVal(p,"total");if(total<1||total>10000)throw new BizException("号源总数须在1～10000之间");BigDecimal fee=Rows.decimal(p,"fee");if(fee.signum()<0||fee.scale()>2)throw new BizException("费用必须为非负数且最多两位小数");String status=Rows.str(p,"status");if(!List.of("OPEN","DRAFT").contains(status))throw new BizException("请通过专用停诊操作停止排班");p.put("start_time",start);p.put("end_time",end);p.put("work_date",day);p.put("period",Rows.required(p,"period",20));p.put("id",id==null?0:id);
        if(id!=null){var old=db.lockSchedule(id);if(old==null||Rows.longVal(old,"doctor_id")!=doctor)throw new BizException("排班不存在或不能更换医生");if("STOPPED".equals(old.get("status")))throw new BizException("停诊排班不能直接重新开放，请新建合法排班");int used=Rows.intVal(old,"total")-Rows.intVal(old,"remaining");if(total<used)throw new BizException("总号源不得少于已占用数量");if(used>0&&(!Rows.dateTime(old,"start_time").equals(start)||!Rows.dateTime(old,"end_time").equals(end)||!Rows.str(old,"period").equals(p.get("period"))||!Rows.str(old,"status").equals(status)))throw new BizException("已有有效挂号，不能变更时段、日期或发布状态");}
        else if(!start.isAfter(LocalDateTime.now(clock)))throw new BizException("不能新增已开始的排班");
        if(db.overlaps(p)>0)throw new BizException("医生已有重叠时段的排班");if(id==null){p.remove("id");db.addSchedule(p);}else db.updateSchedule(p);return Map.of("id",p.get("id"));
    }
    @Audit("药品目录维护") @Transactional public Object drug(Long id,Map<String,Object> in){Actor.current().require("ADMIN");var p=new HashMap<>(in);p.put("code",Rows.required(p,"code",40));p.put("name",Rows.required(p,"name",100));p.putIfAbsent("spec","");p.putIfAbsent("unit","盒");p.putIfAbsent("threshold",10);p.putIfAbsent("enabled",true);if(Rows.decimal(p,"price").signum()<0||Rows.decimal(p,"price").scale()>2||Rows.intVal(p,"threshold")<0)throw new BizException("药价或库存阈值无效");if(id==null)db.addDrug(p);else{if(db.lockDrug(id)==null)throw new BizException("药品不存在");p.put("id",id);db.updateDrug(p);}return Map.of("id",p.get("id"));}
    @Audit("库存调整") @Transactional public Object adjust(long id,Map<String,Object> in){Actor a=Actor.current();a.require("PHARMACIST");var p=new HashMap<>(in);int q=Rows.intVal(p,"quantity");if(q==0)throw new BizException("调整数量不能为0");p.put("reason",Rows.required(p,"reason",500));p.put("id",id);p.put("actor_id",a.id());if(db.lockDrug(id)==null)throw new BizException("药品不存在");if(db.adjust(p)!=1)throw new BizException("调整后库存不能低于已预占数量");db.movement(p);return db.lockDrug(id);}
    public Object stats(){Actor.current().require("ADMIN");var date=LocalDate.now(clock);Map<String,Object> p=Map.of("from",date.atStartOfDay(),"to",date.plusDays(1).atStartOfDay());var received=db.income(p);var refunded=db.refunds(p);return Map.of("registrations",db.registrationCount(p),"completed_visits",db.completedCount(p),"received",received,"refunded",refunded,"net_income",received.subtract(refunded),"low_stock",db.lowStock(),"department_counts",db.departmentCounts(p));}
}
