package com.example.hospital.business;

import java.util.*;
import java.time.LocalDateTime;
import org.apache.ibatis.annotations.*;

@Mapper
public interface BusinessMapper {
    @Select("SELECT * FROM app_user WHERE id=#{id} FOR UPDATE") Map<String,Object> lockUser(long id);
    @Select("SELECT * FROM doctor WHERE id=#{id} FOR UPDATE") Map<String,Object> lockDoctor(long id);
    @Select("SELECT * FROM schedule WHERE id=#{id}") Map<String,Object> schedule(long id);
    @Select("SELECT * FROM schedule WHERE id=#{id} FOR UPDATE") Map<String,Object> lockSchedule(long id);
    @Select("SELECT * FROM registration WHERE id=#{id}") Map<String,Object> registration(long id);
    @Select("SELECT * FROM registration WHERE id=#{id} FOR UPDATE") Map<String,Object> lockRegistration(long id);
    @Select("SELECT * FROM registration WHERE patient_id=#{patientId} AND request_key=#{requestKey} FOR UPDATE") Map<String,Object> byRequest(@Param("patientId")long patientId,@Param("requestKey")String requestKey);
    @Select("SELECT * FROM registration WHERE patient_id=#{patientId} AND schedule_id=#{scheduleId} AND active_flag=1 FOR UPDATE") Map<String,Object> activeRegistration(@Param("patientId")long patientId,@Param("scheduleId")long scheduleId);
    @Update("UPDATE schedule SET remaining=remaining-1 WHERE id=#{id} AND remaining>0 AND status='OPEN' AND start_time>#{now}") int takeSlot(@Param("id")long id,@Param("now")LocalDateTime now);
    @Update("UPDATE schedule SET remaining=remaining+1 WHERE id=#{id} AND remaining<total") int releaseSlot(long id);
    @Insert("INSERT INTO registration(patient_id,schedule_id,request_key,status,deadline) VALUES(#{patient_id},#{schedule_id},#{request_key},'RESERVED',#{deadline})") @Options(useGeneratedKeys=true,keyProperty="id") int insertRegistration(Map<String,Object> row);
    @Update("UPDATE registration SET status=#{status},cancel_reason=#{reason} WHERE id=#{id}") int registrationState(@Param("id")long id,@Param("status")String status,@Param("reason")String reason);
    @Insert("INSERT INTO bill(registration_id,patient_id,prescription_id,type,status,amount,deadline) VALUES(#{registration_id},#{patient_id},#{prescription_id},#{type},'UNPAID',#{amount},#{deadline})") @Options(useGeneratedKeys=true,keyProperty="id") int insertBill(Map<String,Object> row);
    @Select("SELECT * FROM bill WHERE id=#{id}") Map<String,Object> bill(long id);
    @Select("SELECT * FROM bill WHERE id=#{id} FOR UPDATE") Map<String,Object> lockBill(long id);
    @Select("SELECT * FROM bill WHERE registration_id=#{id} AND type='REGISTRATION' FOR UPDATE") Map<String,Object> registrationBill(long id);
    @Select("SELECT * FROM bill WHERE prescription_id=#{id} ORDER BY id DESC LIMIT 1 FOR UPDATE") Map<String,Object> prescriptionBill(long id);
    @Update("UPDATE bill SET status=#{status},paid_at=CASE WHEN #{status}='PAID' THEN #{now} ELSE paid_at END,refund_at=CASE WHEN #{status}='REFUNDED' THEN #{now} ELSE refund_at END WHERE id=#{id}") int billState(@Param("id")long id,@Param("status")String status,@Param("now")LocalDateTime now);
    @Update("UPDATE bill SET refund_requested=TRUE WHERE id=#{id}") int requestRefund(long id);
    @Insert("INSERT INTO payment_record(bill_id,patient_id,actor_id,amount,transaction_no) VALUES(#{id},#{patient_id},#{actor_id},#{amount},#{transaction_no})") int insertPayment(Map<String,Object> row);
    @Insert("INSERT INTO refund_record(bill_id,patient_id,actor_id,amount,transaction_no,reason) VALUES(#{id},#{patient_id},#{actor_id},#{amount},#{transaction_no},#{reason})") int insertRefund(Map<String,Object> row);
    @Select("SELECT id FROM bill WHERE status='UNPAID' AND deadline<=#{now} ORDER BY deadline,id LIMIT 100") List<Long> expiredBills(LocalDateTime now);
    @Select("SELECT * FROM visit WHERE id=#{id}") Map<String,Object> visit(long id);
    @Select("SELECT * FROM visit WHERE id=#{id} FOR UPDATE") Map<String,Object> lockVisit(long id);
    @Select("SELECT * FROM visit WHERE registration_id=#{id} FOR UPDATE") Map<String,Object> registrationVisit(long id);
    @Update("UPDATE schedule SET next_queue=next_queue+1 WHERE id=#{id}") int nextQueue(long id);
    @Insert("INSERT INTO visit(registration_id,patient_id,doctor_id,schedule_id,queue_no,sort_no,status) VALUES(#{registration_id},#{patient_id},#{doctor_id},#{schedule_id},#{queue_no},#{sort_no},'WAITING')") @Options(useGeneratedKeys=true,keyProperty="id") int insertVisit(Map<String,Object> row);
    @Select("SELECT id FROM visit WHERE doctor_id=#{id} AND status IN ('CALLED','IN_PROGRESS') LIMIT 1") Long currentVisit(long id);
    @Select("SELECT id FROM visit WHERE schedule_id=#{id} AND status='WAITING' ORDER BY sort_no LIMIT 1") Long firstWaiting(long id);
    @Update("UPDATE visit SET status=#{status},called_at=CASE WHEN #{status}='CALLED' THEN #{now} ELSE called_at END,started_at=CASE WHEN #{status}='IN_PROGRESS' THEN #{now} ELSE started_at END,completed_at=CASE WHEN #{status}='COMPLETED' THEN #{now} ELSE completed_at END WHERE id=#{id}") int visitState(@Param("id")long id,@Param("status")String status,@Param("now")LocalDateTime now);
    @Update("UPDATE visit SET sort_no=#{sortNo},status='WAITING' WHERE id=#{id}") int requeue(@Param("id")long id,@Param("sortNo")int sortNo);
    @Select("SELECT COUNT(*) FROM queue_event WHERE visit_id=#{visitId} AND action='REQUEUE' AND request_key=#{key}") int requeueExists(@Param("visitId")long visitId,@Param("key")String key);
    @Insert("INSERT INTO queue_event(visit_id,action,actor_id,request_key) VALUES(#{visitId},#{action},#{actorId},#{key})") int queueEvent(@Param("visitId")long visitId,@Param("action")String action,@Param("actorId")Long actorId,@Param("key")String key);
    @Select("SELECT * FROM medical_record WHERE visit_id=#{id}") Map<String,Object> record(long id);
    @Insert("INSERT INTO medical_record(visit_id,patient_id,doctor_id,chief_complaint,history,past_history,allergies,diagnosis,advice,status,draft_items,submitted_at) VALUES(#{visit_id},#{patient_id},#{doctor_id},#{chief_complaint},#{history},#{past_history},#{allergies},#{diagnosis},#{advice},#{status},#{draft_items},#{submitted_at}) ON DUPLICATE KEY UPDATE chief_complaint=VALUES(chief_complaint),history=VALUES(history),past_history=VALUES(past_history),allergies=VALUES(allergies),diagnosis=VALUES(diagnosis),advice=VALUES(advice),status=VALUES(status),draft_items=VALUES(draft_items),submitted_at=VALUES(submitted_at)") int saveRecord(Map<String,Object> row);
    @Select("SELECT * FROM prescription WHERE id=#{id}") Map<String,Object> prescription(long id);
    @Select("SELECT * FROM prescription WHERE id=#{id} FOR UPDATE") Map<String,Object> lockPrescription(long id);
    @Select("SELECT * FROM prescription WHERE visit_id=#{id} ORDER BY id DESC") List<Map<String,Object>> visitPrescriptions(long id);
    @Select("SELECT * FROM prescription_item WHERE prescription_id=#{id} ORDER BY drug_id") List<Map<String,Object>> items(long id);
    @Insert("INSERT INTO prescription(visit_id,patient_id,doctor_id,status,amount,replaces_id) VALUES(#{visit_id},#{patient_id},#{doctor_id},'UNPAID',#{amount},#{replaces_id})") @Options(useGeneratedKeys=true,keyProperty="id") int insertPrescription(Map<String,Object> row);
    @Insert("INSERT INTO prescription_item(prescription_id,drug_id,drug_name,spec,unit,unit_price,quantity,usage_text) VALUES(#{prescription_id},#{drug_id},#{drug_name},#{spec},#{unit},#{unit_price},#{quantity},#{usage_text})") int insertItem(Map<String,Object> row);
    @Update("UPDATE prescription SET status=#{status},dispensed_at=CASE WHEN #{status}='DISPENSED' THEN #{now} ELSE dispensed_at END WHERE id=#{id}") int prescriptionState(@Param("id")long id,@Param("status")String status,@Param("now")LocalDateTime now);
    @Select("SELECT * FROM drug WHERE id=#{id} FOR UPDATE") Map<String,Object> lockDrug(long id);
    @Update("UPDATE drug SET reserved=reserved+#{qty} WHERE id=#{id} AND enabled=TRUE AND stock-reserved>=#{qty}") int reserveDrug(@Param("id")long id,@Param("qty")int qty);
    @Update("UPDATE drug SET reserved=reserved-#{qty} WHERE id=#{id} AND reserved>=#{qty}") int releaseDrug(@Param("id")long id,@Param("qty")int qty);
    @Update("UPDATE drug SET stock=stock-#{qty},reserved=reserved-#{qty} WHERE id=#{id} AND stock>=#{qty} AND reserved>=#{qty}") int dispenseDrug(@Param("id")long id,@Param("qty")int qty);
    @Insert("INSERT INTO stock_movement(drug_id,actor_id,business_id,type,quantity,reason,created_at) VALUES(#{drugId},#{actorId},#{businessId},#{type},#{quantity},#{reason},CURRENT_TIMESTAMP(6))") int stockMovement(@Param("drugId")long drugId,@Param("actorId")Long actorId,@Param("businessId")long businessId,@Param("type")String type,@Param("quantity")int quantity,@Param("reason")String reason);
    @Update("UPDATE schedule SET status='STOPPED',reason=#{reason} WHERE id=#{id}") int stopSchedule(@Param("id")long id,@Param("reason")String reason);
    @Select("SELECT id FROM registration WHERE schedule_id=#{id} AND status IN ('RESERVED','BOOKED') ORDER BY id") List<Long> scheduleRegistrations(long id);
    @Select("SELECT COUNT(*) FROM visit WHERE schedule_id=#{id} AND status IN ('WAITING','CALLED','IN_PROGRESS')") int waitingCount(long id);
    @Update("UPDATE visit SET status='NO_SHOW' WHERE schedule_id=#{id} AND status='SKIPPED'") int skippedNoShow(long id);
    @Select("SELECT COUNT(*) FROM visit WHERE doctor_id=#{doctorId} AND patient_id=#{patientId} AND status IN ('IN_PROGRESS','COMPLETED')") int treatmentRelation(@Param("doctorId")long doctorId,@Param("patientId")long patientId);
    List<Map<String,Object>> departments(Map<String,Object> query);
    List<Map<String,Object>> doctors(Map<String,Object> query);
    List<Map<String,Object>> schedules(Map<String,Object> query);
    List<Map<String,Object>> drugs(Map<String,Object> query);
    List<Map<String,Object>> registrations(Map<String,Object> query);
    List<Map<String,Object>> bills(Map<String,Object> query);
    List<Map<String,Object>> visits(Map<String,Object> query);
    List<Map<String,Object>> records(Map<String,Object> query);
    List<Map<String,Object>> prescriptions(Map<String,Object> query);
    List<Map<String,Object>> payments(Map<String,Object> query);
    List<Map<String,Object>> refunds(Map<String,Object> query);
}
