<script setup>
import { onMounted, ref } from 'vue'
import { get, post, confirmAction, perform } from '../api'
import { useAuth } from '../stores/auth'
import StatusTag from '../components/StatusTag.vue'
const auth = useAuth(), rows = ref([]), loading = ref(false), error = ref(''), filter = ref('')
const isStaff = auth.role === 'CASHIER'
async function load () { loading.value = true; error.value = ''; try { rows.value = await get('/bills', { status: filter.value || undefined, size: 100 }) } catch (e) { error.value = e.message } finally { loading.value = false } }
async function pay (row) { await perform(() => post(`/bills/${row.id}/pay`, { simulate_failure: false }), load, '缴费成功') }
async function refund (row) { if (await confirmAction('确认办理这笔整单退款吗？')) await perform(() => post(`/bills/${row.id}/refund`), load, '退款成功') }
async function requestRefund (row) { if (await confirmAction('确认申请药费退款吗？申请后由收费员办理。')) await perform(() => post(`/bills/${row.id}/request-refund`), load, '已提交退款申请') }
onMounted(load)
</script>
<template><div><div class="page-heading"><div><div class="eyebrow">PAYMENT</div><h1>门诊缴费</h1><p>{{ isStaff ? '检索患者账单并办理模拟收费与退款。' : '挂号费与药费分别结算，金额以服务端账单为准。' }}</p></div><el-button @click="load" :loading="loading">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon/><section class="panel"><div class="filters"><el-select v-model="filter" placeholder="全部状态" clearable @change="load"><el-option label="待支付" value="UNPAID"/><el-option label="已支付" value="PAID"/><el-option label="已退款" value="REFUNDED"/><el-option label="已关闭" value="CLOSED"/></el-select></div><el-table :data="rows" v-loading="loading" empty-text="暂无账单" stripe><el-table-column prop="id" label="账单号" width="90"/><el-table-column prop="type" label="类型"><template #default="s">{{ s.row.type === 'REGISTRATION' ? '挂号费' : '处方药费' }}</template></el-table-column><el-table-column prop="doctor_name" label="医生"/><el-table-column prop="patient_name" label="患者" v-if="isStaff"/><el-table-column prop="amount" label="金额"><template #default="s"><span class="money">¥{{ Number(s.row.amount || 0).toFixed(2) }}</span></template></el-table-column><el-table-column prop="status" label="状态"><template #default="s"><StatusTag :value="s.row.status"/></template></el-table-column><el-table-column prop="deadline" label="截止时间" min-width="170"/><el-table-column label="操作" width="220"><template #default="s"><div class="table-actions"><el-button v-if="s.row.status==='UNPAID'" type="primary" size="small" @click="pay(s.row)">{{ isStaff ? '代缴' : '立即缴费' }}</el-button><el-button v-if="s.row.status==='PAID' && s.row.type==='REGISTRATION'" type="warning" plain size="small" @click="refund(s.row)">退款</el-button><el-button v-if="s.row.status==='PAID' && s.row.type==='PRESCRIPTION' && !isStaff" type="warning" plain size="small" @click="requestRefund(s.row)" :disabled="!!s.row.refund_requested">{{ s.row.refund_requested ? '已申请退款' : '申请退款' }}</el-button><el-button v-if="s.row.status==='PAID' && s.row.type==='PRESCRIPTION' && isStaff" type="warning" plain size="small" @click="refund(s.row)">{{ s.row.refund_requested ? '办理申请退款' : '办理退款' }}</el-button></div></template></el-table-column></el-table></section></div></template>
