<script setup>
import { computed, onMounted, ref } from 'vue'
import { Calendar, Tickets, Wallet, Document, FirstAidKit, Box, User, Operation, Collection, Refresh } from '@element-plus/icons-vue'
import { useAuth } from '../stores/auth'
import { get } from '../api'
import { money, roles, today } from '../utils'
const auth = useAuth(), loading = ref(false), error = ref(''), stats = ref({}), recent = ref([])
const quickLinks = computed(() => ({ PATIENT: [['/schedules','预约挂号','查找科室与出诊医生',Calendar],['/registrations','我的挂号','缴费、报到与退号',Tickets],['/bills','门诊缴费','查看挂号费与处方药费',Wallet],['/records','电子病历','查看已完成就诊记录',Document]], DOCTOR: [['/visits','接诊工作台','叫号、病历与处方',FirstAidKit],['/schedules','我的排班','查看近期出诊安排',Calendar],['/records','历史病历','按接诊关系查询',Document],['/prescriptions','处方管理','核对与更换处方',Box]], CASHIER: [['/bills','收费工作台','检索患者账单与退款',Wallet],['/profile','个人资料','查看账户资料',User]], PHARMACIST: [['/prescriptions','核对发药','已付款处方的发药处理',Box],['/inventory','药房库存','入库、调整与库存流水',Collection]], ADMIN: [['/manage/schedules','排班号源','维护出诊与停诊安排',Calendar],['/manage/users','人员账户','管理角色与账户状态',User],['/inventory','库存概览','查看库存与低库存药品',Collection],['/advanced','队列与任务','排队状态与自动排班',Operation]] }[auth.role] || []))
const cards = computed(() => auth.role === 'ADMIN' ? [ ['今日挂号',stats.value.registrations ?? '—','按挂号创建时间统计',Tickets],['今日完成就诊',stats.value.completed_visits ?? '—','按完成时间统计',FirstAidKit],['今日净收',money(stats.value.net_income),'实收金额减退款金额',Wallet],['低库存药品',stats.value.low_stock ?? '—','可用库存达到预警阈值',Box] ] : auth.role === 'PATIENT' ? [['待支付账单',stats.value.unpaid ?? '—','前 100 条账单中的待支付',Wallet],['有效挂号',stats.value.active ?? '—','前 100 条挂号中的有效记录',Tickets],['待完成就诊',stats.value.waiting ?? '—','前 100 条就诊中的待完成',FirstAidKit],['我的病历',stats.value.records ?? '—','最近病历记录（最多 100 条）',Document]] : [['待处理事项',stats.value.pending ?? '—','最近 100 条记录中的待处理',Tickets],['已完成事项',stats.value.finished ?? '—','最近 100 条记录中的已完成',FirstAidKit],['工作身份',roles[auth.role],'按身份开放业务功能',User],['服务日期',today().slice(5),'业务时间使用北京时间',Calendar]])
async function load() { loading.value = true; error.value = ''; try {
  if (auth.role === 'ADMIN') stats.value = await get('/admin/stats')
  else if (auth.role === 'PATIENT') { const [bills,regs,visits,records] = await Promise.all([get('/bills',{size:100}),get('/registrations',{size:100}),get('/visits',{size:100}),get('/records',{size:100})]); stats.value = { unpaid:bills.filter(x=>x.status==='UNPAID').length,active:regs.filter(x=>['RESERVED','BOOKED'].includes(x.status)).length,waiting:visits.filter(x=>['WAITING','CALLED','IN_PROGRESS'].includes(x.status)).length,records:records.length } }
  else { const list = await get(auth.role === 'DOCTOR' ? '/visits' : auth.role === 'CASHIER' ? '/bills' : '/prescriptions',{size:100}); stats.value = {pending:list.filter(x=>['WAITING','CALLED','IN_PROGRESS','UNPAID',...(auth.role==='PHARMACIST'?['PAID']:[])].includes(x.status)).length,finished:list.filter(x=>['COMPLETED','DISPENSED',...(auth.role==='CASHIER'?['PAID']:[])].includes(x.status)).length} }
} catch(e) {error.value=e.message} finally {loading.value=false} }
onMounted(load)
</script>
<template><div><div class="page-heading"><div><div class="eyebrow">OVERVIEW</div><h1>工作概览</h1><p>{{ today() }} · 在这里了解门诊动态，开始今天的服务。</p></div><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"/><section class="welcome-banner"><span class="banner-cross">✚</span><h1>{{ auth.user?.display_name }}，您好</h1><p>{{ auth.role === 'PATIENT' ? '提前预约，按时到诊。您可以在线完成挂号与缴费，报到后随时查看候诊进度。' : '每一个环节都紧密相连。请核对患者与业务状态，完成您负责的门诊服务。' }}</p></section><div v-loading="loading" class="stats-grid"><div v-for="[name,value,note,icon] in cards" :key="name" class="stat-card"><div class="stat-icon"><el-icon><component :is="icon"/></el-icon></div><div class="stat-label">{{ name }}</div><div class="stat-value">{{ value }}</div><div class="stat-note">{{ note }}</div></div></div><div class="two-column"><section class="panel"><div class="panel-header"><div><h2>常用服务</h2><p>从这里快速进入您的工作环节</p></div></div><div class="quick-grid"><router-link v-for="[path,title,desc,icon] in quickLinks" :key="path" :to="path" class="quick-item"><el-icon><component :is="icon"/></el-icon><div><strong>{{ title }}</strong><small>{{ desc }}</small></div></router-link></div><template v-if="auth.role === 'ADMIN'"><div class="panel-header" style="margin-top:30px"><h2>今日科室挂号量</h2></div><div v-for="item in stats.department_counts || []" :key="item.name" class="chart-bar-row"><span>{{ item.name }}</span><div class="chart-bar"><i :style="{width:`${Number(item.count) / Math.max(1,...(stats.department_counts || []).map(x=>Number(x.count))) * 100}%`}"></i></div><b>{{ item.count }}</b></div><el-empty v-if="!stats.department_counts?.length" description="今日暂无科室挂号记录" :image-size="55"/><p class="muted">今日实收 {{ money(stats.received) }} · 今日退款 {{ money(stats.refunded) }}；金额按交易成功时间统计。</p></template></section><section class="panel"><div class="panel-header"><h2>就诊服务指引</h2></div><div v-for="(step,index) in [['预约与缴费','选择排班后，在账单截止时间前缴费。'],['报到与候诊','时段开始前 30 分钟开放报到，关注叫号。'],['门诊接诊','医生完成病历并根据实际需要开具处方。'],['药费与取药','支付药费后，由药师核对并发药。']]" :key="index" class="flow-step"><span class="step-number">{{ String(index + 1).padStart(2,'0') }}</span><div><strong>{{ step[0] }}</strong><p>{{ step[1] }}</p></div></div></section></div></div></template>
