-- 在专用 hospital 数据库内执行；不包含 DROP，不修改其他数据库。
CREATE TABLE IF NOT EXISTS app_user (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(64) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL, display_name VARCHAR(80) NOT NULL,
 role VARCHAR(20) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 CHECK(role IN('PATIENT','DOCTOR','CASHIER','PHARMACIST','ADMIN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS patient_profile (
 user_id BIGINT PRIMARY KEY, phone VARCHAR(30),birth_date DATE,allergies VARCHAR(500),
 FOREIGN KEY(user_id) REFERENCES app_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS department (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100) NOT NULL UNIQUE,location VARCHAR(100),description VARCHAR(500),enabled BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS doctor (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT NOT NULL UNIQUE,department_id BIGINT NOT NULL,title VARCHAR(60),specialty VARCHAR(500),enabled BOOLEAN NOT NULL DEFAULT TRUE,
 FOREIGN KEY(user_id) REFERENCES app_user(id),FOREIGN KEY(department_id) REFERENCES department(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS schedule (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,doctor_id BIGINT NOT NULL,work_date DATE NOT NULL,period VARCHAR(20) NOT NULL,
 start_time DATETIME(6) NOT NULL,end_time DATETIME(6) NOT NULL,total INT NOT NULL,remaining INT NOT NULL,fee DECIMAL(10,2) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'OPEN',reason VARCHAR(500),next_queue INT NOT NULL DEFAULT 0,source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
 UNIQUE KEY uk_schedule(doctor_id,work_date,period),KEY idx_schedule_date(work_date,status),
 FOREIGN KEY(doctor_id) REFERENCES doctor(id),CHECK(total>0 AND remaining>=0 AND remaining<=total AND fee>=0),CHECK(end_time>start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS drug (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,code VARCHAR(40) NOT NULL UNIQUE,name VARCHAR(100) NOT NULL,spec VARCHAR(100),unit VARCHAR(30),price DECIMAL(10,2) NOT NULL,
 stock INT NOT NULL DEFAULT 0,reserved INT NOT NULL DEFAULT 0,threshold INT NOT NULL DEFAULT 10,enabled BOOLEAN NOT NULL DEFAULT TRUE,
 CHECK(stock>=reserved AND reserved>=0 AND price>=0 AND threshold>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS stock_movement (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,drug_id BIGINT NOT NULL,actor_id BIGINT,business_id BIGINT,type VARCHAR(30) NOT NULL,quantity INT NOT NULL,reason VARCHAR(500),created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 KEY idx_movement(drug_id,created_at),FOREIGN KEY(drug_id) REFERENCES drug(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS operation_log (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,actor_id BIGINT,operation VARCHAR(100) NOT NULL,request_id VARCHAR(80),success BOOLEAN NOT NULL,detail VARCHAR(1000),created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 KEY idx_audit(created_at,operation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
